### ISSUE TITLE
Error Updating with Caali-Proxy

### ISSUE THREAD

**Issue by HarveyEV** [SaltyMonkey/NoMoreAnnoyingTitles#2]
[update] ERROR: Unable to auto-update module no-more-annoying-titles:
Failed to update the following module files:
 - module.json
 - ERROR: https://raw.githubusercontent.com/SaltyMonkey/NoMoreAnnoyingTitles/master/module.json
Downloaded file doesn't match hash specified in patch manifest! Possible causes:
   + Incorrect manifest specified by module developer
   + NoPing (if you're using it) has a bug that can fuck up the download

Any ideas would be owesum.

**Comment by SaltyMonkey** [comment]
should be fixed in https://github.com/SaltyMonkey/NoMoreAnnoyingTitles/commit/10195cb3bb9cfc4503659363f65c8c5c4097a485
